namespace: robberts-assistent
resources:
- sealed-secret-robberts-assistent.yaml
- robberts-assistent-backend-deployment.yaml
- robberts-assistent-backend-service.yaml
- robberts-assistent-frontend-deployment.yaml
- robberts-assistent-frontend-service.yaml
- robberts-assistent-frontend-route.yaml
- groentetuin-frontend-deployment.yaml
- groentetuin-frontend-service.yaml
- groentetuin-frontend-route.yaml
images:
- name: ghcr.io/robbertvdzon/groentetuin-frontend
  newName: ghcr.io/robbertvdzon/groentetuin-frontend
  newTag: sha-3e951db
- name: ghcr.io/robbertvdzon/robberts-assistent-backend
  newName: ghcr.io/robbertvdzon/robberts-assistent-backend
  newTag: sha-838d379
- name: ghcr.io/robbertvdzon/robberts-assistent-frontend
  newName: ghcr.io/robbertvdzon/robberts-assistent-frontend
  newTag: sha-c4c2eee
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
